### ISSUE TITLE
Link roto en FAQ de telegram

### ISSUE THREAD

**Issue by ssoto** [python-spain/PMF#13]
Buenas,
he visto que el enlace que aparece en la página  [Yes, Python is Slow, and I Don’t Care](https://github.com/python-spain/PMF/issues/new) ya no existe.
Sólo por informar y actualizar la página.
Un saludo!

**Comment by ssoto** [comment]
Bueno, y el segundo [10 Myths of Enterprise Python](https://www.paypal-engineering.com/2014/12/10/10-myths-of-enterprise-python/) tampoco lleva donde debería. Por lo que se ve borraron o modificaron el título del artículo y medium cuando caes en este te lleva al espaciod e Paypal en vez de al artículo en concreto.

**Comment by quobit** [comment]
Gracias @ssoto !
