### ISSUE TITLE
Aprende Python

### ISSUE THREAD

**Issue by sdelquin** [python-spain/PMF#15]
Hola!

Enhorabuena por la recopilación de recursos para aprender Python en https://es.python.org/pages/aprende-python.html. Me parece genial.

¿Se podría añadir https://aprendepython.es? Yet another Python learning page jeje (hecha por mi)

Gracias.

Saludos,
Sergio.

**Comment by quobit** [comment]
Disculpa @sdelquin 

Vi de casualidad tu web y la añadí aquí sin darme cuenta de que habías abierto un tique. Enhorabuena por el resultado
